name: "Assign Guide"
on:
  pull_request:
    types: [opened,synchronize]
    
jobs:
  GreetCommitter:    
    runs-on: ubuntu-latest
    steps:
    - name: "Greet contributor"
      uses: ibakshay/greet-contributors-action@v3
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        content: "
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed."
